apiVersion: apps/v1
kind: Deployment
metadata:
  name: mroh-rfs-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mroh-rfs-backend
  template:
    metadata:
      labels:
        app: mroh-rfs-backend
    spec:
      containers:
      - name: mroh-rfs-backend
        image: mrohcontainerregistrybh.azurecr.io/mroh-rfs-backend:latest        
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"