services:
  db:
    image: postgres:14-alpine
    container_name: modular_monolith_db
    environment:
      POSTGRES_DB: modular_monolith_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
